services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facedoor_admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://user:password@tcp(db:3306)/face_door_admin_panel",
      "up"
    ]
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: face_door_admin_panel
    ports:
      - "8081:8080"
    depends_on:
      - db
      - migrate

volumes:
  mysql_data:
